### ISSUE TITLE
TODO: Update biosut v1.0.0

### ISSUE THREAD

**Issue by jlli6t** [jlli6t/biosut#1]
Improvements included in new version:

- [x] Big change of coding style

- [x] Add alignment related module, e.g. diamond, blast, hmmscan, integrage blast, diamond, hmmscan, these aligners together maybe?

- [x] Update bam util
